import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/nav-bar/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div className="p-4">{children}</div>
      </body>
    </html>
  );
}
